### PR TITLE
fix: fix compilation on darwin

### PR DESCRIPTION
**Pull request by keyvank**
(This will break `rust-fil-nse-gpu` since `GPUSelector` has been moved from `neptune::cl::GPUSelector` to `neptune::GPUSelector`)

### CODE REVIEW

**Comment by porcuquine** [comment]
@keyvank I've approved this, but before we merge can you explain why the CI job never got added? Was it impossible to reproduce the problem which prompted this? Even if so, I think we should (independently) have such a job, so let's create an issue and do that as a follow-up (if not here/now).

If it was impossible, why?

**Comment by porcuquine** [comment]
Ah, I do see #48 now.

**Comment by porcuquine** [comment]
Please rebase now that #48 is merged.

**Comment by keyvank** [comment]
@porcuquine 
Rebased.
The problem was that Go linker (In MacOS) was not able to link the binary that was produced by rustc and had neptune-triton stuff in it (With no errors)  (For some unknown reasons we didn't figure out). The solution was to prevent neptune::cl (Which had neptune-triton calls in it) from compiling on macos with a conditional compilation flag. I may be able to reproduce this by linking the produced binary with a dummy Go program in a separate CI job.

**Comment by porcuquine** [comment]
> I may be able to reproduce this by linking the produced binary with a dummy Go program in a separate CI job.

That's unnecessary. Let's not.

**Pull request merged**
