### PR TITLE
Poseidon spec

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
Adds a PDF version of the [Poseidon spec](https://github.com/filecoin-project/specs/pull/1252).

### CODE REVIEW

**Review by porcuquine — COMMENTED** [review]
I still think we should link to the spec itself, rather than to a personal HackMD page. The best thing is probably to merge the spec PR, then create a PDF exactly corresponding to what landed there. (If what is here now ends up being that, that's fine.) Then, we can merge this one and include exactly what landed there.

https://github.com/filecoin-project/neptune/pull/84#pullrequestreview-610293420

**Comment by dignifiedquire** [comment]
@DrPeterVanNostrand @porcuquine what's the state here?

**Comment by DrPeterVanNostrand** [comment]
It looks like it's missing some corrections that I made when updating the `specs` repo's version. I'll create a new PDF and update this PR

**Comment by porcuquine** [comment]
If you also replace the link to your personal HackMD with a link to the Filecoin spec itself, then I think this should be ready to go.

**Comment by DrPeterVanNostrand** [comment]
I have pushed the PDF to this repo and changed the README.

**Comment by porcuquine** [comment]
Looks good, but the link is dead, since apparently the spec PR has not merged yet. Let's get that done and finish this.

**Comment by DrPeterVanNostrand** [comment]
@porcuquine The Poseidon spec was merged into the `specs` repo, so the link in this README is good (https://spec.filecoin.io/#section-algorithms.crypto.poseidon).

**Review by porcuquine — APPROVED** [review]
Looks good. It wouldn't hurt to link from the main README too, but links are good to go now.

**Comment by DrPeterVanNostrand** [comment]
Would it be better to just move this README into the top-level's README and move the PDF into the top-level?

**Comment by porcuquine** [comment]
Yeah, that's probably the best way.

**Comment by DrPeterVanNostrand** [comment]
Ok, will do now

**Comment by DrPeterVanNostrand** [comment]
Done.

**Pull request merged**
