### PR TITLE
Halo2: Updates from latest master

### PR DESCRIPTION
**Pull request by storojs72**
This PR updates halo2 branch of `neptune` to 0.8.1 as it is in master currently and fixes halo2 <-> master "behind" divergence. 

It is required for updating halo2 branch of `rust-fil-proofs` eventually.

@vmx, @DrPeterVanNostrand, I guess, You are aware of `master` commits, so I would ask to review https://github.com/filecoin-project/neptune/pull/168/commits/9ac186ebbd67fb342e86511111662bd0945b4fd9 more carefully than others, as it contains merge conflicts fixes.

### CODE REVIEW

**Comment by vmx** [comment]
I think https://github.com/filecoin-project/neptune/tree/halo2-gpu is already doing most of this.

**Comment by storojs72** [comment]
> I think https://github.com/filecoin-project/neptune/tree/halo2-gpu is already doing most of this.

Yeah, thanks for pointing. We can pick changes from your branch into `halo2` instead, if you prefer. Anyway, it looks like that having single, unified branch with Halo2 "source of trust" is beneficial

**Review by DrPeterVanNostrand — APPROVED** [review]
Looks good to me

**Review by vmx — CHANGES_REQUESTED** [review]
I'd prefer if we just force-push the `halo2-gpu` branch as `halo2` as it has a linear history.

**Comment by storojs72** [comment]
@vmx , I don't mind using `halo2-gpu`. Actually, I didn't know that it exists with necessary changes until you mentioned. What if we use it but rename it to `halo2`? Commit history will be still preserved, but there will be no confusion about single source of Halo2 work along the repositories. WDYT?

**Comment by vmx** [comment]
@storojs72 I've force-pushed `halo2-gpu` as `halo2` (and pushed the former `halo2` as `halo2-jake` in case he still needs it. Force-pushing `halo2` branches isn't such a big deal as only our team is using it atm. I think this PR can be closed and the branch can be deleted once you've updated https://github.com/filecoin-project/rust-fil-proofs/pull/1656.

**Comment by storojs72** [comment]
@vmx , thank you. I'm picking `halo2` branch of neptune and testing https://github.com/filecoin-project/rust-fil-proofs/pull/1656 right now

**Comment by storojs72** [comment]
https://github.com/filecoin-project/rust-fil-proofs/pull/1656 is working with updated `halo2` branch, which seems to be the relevant source of Halo2 stuff (@vmx thank you!). So this PR is not needed anymore.

**Pull request closed without merging**
