### PR TITLE
Add TreeBuilder (with no columns).

### PR DESCRIPTION
**Pull request by porcuquine**
Sometimes we want to create trees without columns. This PR adds support for that by breaking the tree-building component of `ColumnTreeBuilder` out into `TreeBuilder`. The `ColumnTreeBuilder` interface is unchanged, but the tree-building responsibilities are now delegated to an inner `TreeBuilder`.

### CODE REVIEW

**Comment by cryptonemo** [comment]
Based on trying to build from `rust-fil-proofs` master, it looks like the `bellperson` dependency needs to be updated to 0.7.0

**Comment by porcuquine** [comment]
> Based on trying to build from `rust-fil-proofs` master, it looks like the `bellperson` dependency needs to be updated to 0.7.0. `paired` also (0.19.0)

See if #19 will fix this for you. If so, please approve, and I will merge.

**Comment by cryptonemo** [comment]
> > Based on trying to build from `rust-fil-proofs` master, it looks like the `bellperson` dependency needs to be updated to 0.7.0. `paired` also (0.19.0)
> 
> See if #19 will fix this for you. If so, please approve, and I will merge.

Is the link correct?

**Comment by porcuquine** [comment]
> > > Based on trying to build from `rust-fil-proofs` master, it looks like the `bellperson` dependency needs to be updated to 0.7.0. `paired` also (0.19.0)
> > 
> > 
> > See if #19 will fix this for you. If so, please approve, and I will merge.
> 
> Is the link correct?

I meant to link #20.

**Comment by porcuquine** [comment]
@cryptonemo I merged #20 and rebased this. You should be good to go now.

**Comment by porcuquine** [comment]
> Am I missing it, or does the tree builder not account for lc trees? If not, I think particularly in the first cut, that's fine as we can persist the result and compact it.

That's right. This version just supplies the interface needed to generate trees but doesn't throw any data away for you yet.

**Comment by porcuquine** [comment]
I am closing this in favor of #24.

**Pull request closed without merging**
