### PR TITLE
chore: use opencl3 based bellperson and rust-gpu-tools

### PR DESCRIPTION
**Pull request by vmx**

### CODE REVIEW

**Review by dignifiedquire — APPROVED** [review]
lgtm, but @porcuquine should check as well

**Comment by vmx** [comment]
Yes, it's waiting for a proper release. It was supposed to be soon, hence this PR, but plans changed a bit. Though this code will be needed (and probably won't change), so having this properly reviewed already is great.

**Review by porcuquine — APPROVED** [review]
Approved once Git dependencies are updated.

**Comment by porcuquine** [comment]
Is this still waiting for a release? Will need a rebase.

**Review by dignifiedquire — APPROVED** [review]

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
